MODULE=subsys
SUBSYS_MODULE_PATH=.

WARNINGS_AS_ERRORS ?= n
# Target this makefile is building.
# makefile 编译的目标格式
TARGET_TYPE = a

BUILD_PATH_EXT = $(SUBSYS_BUILD_PATH_EXT)

DEPENDENCIES = platform

include ../build/arm-tlm.mk
