INCLUDE_DIRS += $(BOOTLOADER_TYPE_PATH)/inc

LDFLAGS += -Tlinker_$(PLATFORM_DEVICE_LC)_boot.ld
LDFLAGS += -L$(COMMON_BUILD)/linker/arm


LDFLAGS += -Wl,-Map,$(TARGET_BASE).map

ASRC_STARTUP += $(COMMON_BUILD)/startup/arm/startup_$(PLATFORM_DEVICE_LC).S

