
TARGET_COMMUNICATION_LORAWAN_PATH = $(COMMUNICATION_MODULE_PATH)/lorawan

INCLUDE_DIRS += $(TARGET_COMMUNICATION_LORAWAN_PATH)
INCLUDE_DIRS += $(TARGET_COMMUNICATION_LORAWAN_PATH)/board/inc
INCLUDE_DIRS += $(TARGET_COMMUNICATION_LORAWAN_PATH)/crypto/inc
INCLUDE_DIRS += $(TARGET_COMMUNICATION_LORAWAN_PATH)/mac/inc
INCLUDE_DIRS += $(TARGET_COMMUNICATION_LORAWAN_PATH)/mac/src/region
INCLUDE_DIRS += $(TARGET_COMMUNICATION_LORAWAN_PATH)/radio/inc

