
TARGET_COMMUNICATION_LORAWAN_PATH = $(COMMUNICATION_MODULE_PATH)/lorawan

INCLUDE_DIRS += $(TARGET_COMMUNICATION_LORAWAN_PATH)
INCLUDE_DIRS += $(TARGET_COMMUNICATION_LORAWAN_PATH)/boards
INCLUDE_DIRS += $(TARGET_COMMUNICATION_LORAWAN_PATH)/mac
INCLUDE_DIRS += $(TARGET_COMMUNICATION_LORAWAN_PATH)/mac/region
INCLUDE_DIRS += $(TARGET_COMMUNICATION_LORAWAN_PATH)/peripherals
INCLUDE_DIRS += $(TARGET_COMMUNICATION_LORAWAN_PATH)/peripherals/soft-se
INCLUDE_DIRS += $(TARGET_COMMUNICATION_LORAWAN_PATH)/radio
INCLUDE_DIRS += $(TARGET_COMMUNICATION_LORAWAN_PATH)/radio/sx1276
INCLUDE_DIRS += $(TARGET_COMMUNICATION_LORAWAN_PATH)/system

