WIRING_MODULE_NAME=wiring
WIRING_MODULE_PATH ?= $(PROJECT_ROOT)/$(WIRING_MODULE_NAME)
include $(call rwildcard,$(WIRING_MODULE_PATH)/,include.mk)

WIRING_LIB_DIR = $(BUILD_PATH_BASE)/$(WIRING_MODULE_NAME)/$(BUILD_TARGET_PLATFORM)
WIRING_LIB_DEP = $(WIRING_LIB_DIR)/lib$(WIRING_MODULE_NAME).a

