
MODULE=wiring
WIRING_MODULE_PATH=.

# Target this makefile is building.
TARGET_TYPE = a
BUILD_PATH_EXT = $(BUILD_TARGET_PLATFORM)

DEPENDENCIES = hal wiring_ex services system system_ex platform

include ../build/arm-tlm.mk
