TARGET_CMSIS=$(PLATFORM_MCU_PATH)/CMSIS
INCLUDE_DIRS += $(TARGET_CMSIS)/Include
INCLUDE_DIRS += $(TARGET_CMSIS)/Device/ST/Include

TARGET_INTOROBOT_PATH = $(PLATFORM_MCU_PATH)/IntoRobot_Firmware_Driver
INCLUDE_DIRS += $(TARGET_INTOROBOT_PATH)/inc

TARGET_STDPERIPH_PATH = $(PLATFORM_MCU_PATH)/STM32_StdPeriph_Driver
INCLUDE_DIRS += $(TARGET_STDPERIPH_PATH)/inc

TARGET_USB_FS_PATH = $(PLATFORM_MCU_PATH)/STM32_USB_Device_Driver
INCLUDE_DIRS += $(TARGET_USB_FS_PATH)/inc
