SYSTEM_EX_MODULE_NAME=system_ex
SYSTEM_EX_MODULE_PATH?=$(PROJECT_ROOT)/$(SYSTEM_EX_MODULE_NAME)

include $(call rwildcard,$(SYSTEM_EX_MODULE_PATH)/$(PLATFORM_NAME)/inc/,include.mk)

SYSTEM_EX_BUILD_PATH_EXT=$(BUILD_TARGET_PLATFORM)
SYSTEM_EX_LIB_DIR = $(BUILD_PATH_BASE)/$(SYSTEM_EX_MODULE_NAME)/$(SYSTEM_EX_BUILD_PATH_EXT)
SYSTEM_EX_LIB_DEP = $(SYSTEM_EX_LIB_DIR)/lib$(SYSTEM_EX_MODULE_NAME).a

