TARGET_ESP8266_SDK=$(PLATFORM_MCU_PATH)/sdk
INCLUDE_DIRS += $(TARGET_ESP8266_SDK)/include
INCLUDE_DIRS += $(TARGET_ESP8266_SDK)/lwip/include
INCLUDE_DIRS += $(TARGET_ESP8266_SDK)/libc/xtensa-lx106-elf/include

TARGET_INTOROBOT_PATH = $(PLATFORM_MCU_PATH)/IntoRobot_Firmware_Driver
INCLUDE_DIRS += $(TARGET_INTOROBOT_PATH)/inc
INCLUDE_DIRS += $(TARGET_INTOROBOT_PATH)/src/umm_malloc

LIB_DIRS += $(TARGET_ESP8266_SDK)/lib
LIB_DIRS += $(TARGET_ESP8266_SDK)/libc/xtensa-lx106-elf/lib
LIBS +=
