TARGET_ESP8266_SDK=$(PLATFORM_MCU_PATH)/sdk
INCLUDE_DIRS += $(TARGET_ESP8266_SDK)/include
INCLUDE_DIRS += $(TARGET_ESP8266_SDK)/include/json
INCLUDE_DIRS += $(TARGET_ESP8266_SDK)/lwip/include

TARGET_INTOROBOT_PATH = $(PLATFORM_MCU_PATH)/IntoRobot_Firmware_Driver
INCLUDE_DIRS += $(TARGET_INTOROBOT_PATH)/inc

LIB_DIRS += $(TARGET_ESP8266_SDK)/lib
