
TARGET_WIRING_EX_PATH = $(WIRING_EX_MODULE_PATH)
INCLUDE_DIRS += $(TARGET_WIRING_EX_PATH)/$(PLATFORM_NAME)/inc/

# INCLUDE_DIRS += $(TARGET_WIRING_EX_PATH)/$(PLATFORM_NAME)/src/lmic/inc/

# INCLUDE_DIRS += $(TARGET_WIRING_EX_SRC_PATH)/lorawan/crypto/inc
# INCLUDE_DIRS += $(TARGET_WIRING_EX_SRC_PATH)/lorawan/mac/inc
# INCLUDE_DIRS += $(TARGET_WIRING_EX_SRC_PATH)/lorawan/radio/inc
# INCLUDE_DIRS += $(TARGET_WIRING_EX_SRC_PATH)/lorawan/board/inc


