
TARGET_WIRING_EX_PATH = $(WIRING_EX_MODULE_PATH)

INCLUDE_DIRS += $(TARGET_WIRING_EX_PATH)/$(PLATFORM_NAME)/inc
INCLUDE_DIRS += $(TARGET_WIRING_EX_PATH)/$(PLATFORM_NAME)/src
INCLUDE_DIRS += $(TARGET_WIRING_EX_PATH)/$(PLATFORM_NAME)/src/lorawan/crypto/inc
INCLUDE_DIRS += $(TARGET_WIRING_EX_PATH)/$(PLATFORM_NAME)/src/lorawan/mac/inc
INCLUDE_DIRS += $(TARGET_WIRING_EX_PATH)/$(PLATFORM_NAME)/src/lorawan/radio/inc
INCLUDE_DIRS += $(TARGET_WIRING_EX_PATH)/$(PLATFORM_NAME)/src/lorawan/board/inc


