COMMUNICATION_MODULE_NAME = communication
COMMUNICATION_MODULE_PATH ?= $(PROJECT_ROOT)/$(COMMUNICATION_MODULE_NAME)

COMMUNICATION_BUILD_PATH_EXT = $(BUILD_TARGET_PLATFORM)
COMMUNICATION_LIB_DIR = $(BUILD_PATH_BASE)/$(COMMUNICATION_MODULE_NAME)/$(COMMUNICATION_BUILD_PATH_EXT)
COMMUNICATION_LIB_DEP = $(COMMUNICATION_LIB_DIR)/lib$(COMMUNICATION_MODULE_NAME).a

include $(call rwildcard,$(COMMUNICATION_MODULE_PATH)/$(PLATFORM_COMM)/,include.mk)

