
MODULE=communication
COMMUNICATION_MODULE_PATH=.

# Target this makefile is building.
TARGET_TYPE = a

BUILD_PATH_EXT=$(COMMUNICATION_BUILD_PATH_EXT)

DEPENDENCIES = hal wiring wiring_ex services system platform

include ../build/arm-tlm.mk

