WIRING_EX_MODULE_NAME=wiring_ex
WIRING_EX_MODULE_PATH?=$(PROJECT_ROOT)/$(WIRING_EX_MODULE_NAME)

include $(call rwildcard,$(WIRING_EX_MODULE_PATH)/$(PLATFORM_NAME)/inc/,include.mk)

WIRING_EX_LIB_DIR = $(BUILD_PATH_BASE)/$(WIRING_EX_MODULE_NAME)/$(BUILD_TARGET_PLATFORM)
WIRING_EX_LIB_DEP = $(WIRING_EX_LIB_DIR)/lib$(WIRING_EX_MODULE_NAME).a

