
MODULE=wiring_ex
WIRING_EX_MODULE_PATH=.

# Target this makefile is building.
TARGET_TYPE = a
BUILD_PATH_EXT = $(BUILD_TARGET_PLATFORM)

DEPENDENCIES = hal services system wiring platform

include ../build/arm-tlm.mk

