
MODULE=wiring_ex
WIRING_EX_MODULE_PATH=.

# Target this makefile is building.
TARGET_TYPE = a
BUILD_PATH_EXT = $(WIRING_EX_BUILD_PATH_EXT)

DEPENDENCIES = hal services system wiring platform

include ../build/arm-tlm.mk

